### ISSUE TITLE
Upgrading plugin installs beta release

### ISSUE THREAD

**Issue by blairham** [loft-sh/devspace-plugin-loft#2] opened 2020-08-24 15:44 UTC
When installing the plugin it will install a beta release, which can be surprising. I would expect to request to install a beta, otherwise install the latest released version.

**Comment by leventogut** [comment] 2022-01-06 13:48
Hi @blairham,

Thanks for opening the issue; I know this is an old one.

I have tested the behavior with the latest version, and the issue is not seen there; I suspect it is already fixed along the way.

I am closing the issue; you can reopen the issue if you have any problems.

Many thanks

```
# Initial install with no "--version" flag

$ devspace add plugin https://github.com/loft-sh/devspace-plugin-loft
[info]   Installing plugin https://github.com/loft-sh/devspace-plugin-loft
[done] √ Successfully installed plugin https://github.com/loft-sh/devspace-plugin-loft
$ devspace list plugins

 Name   Version   Commands   Vars  
 loft   v2.0.2    18         2     

# Check if we are on the latest version
$ devspace update plugin loft  
[wait] ⠙ Updating plugin loft (0s)
[info]   Current binary is the latest version: 2.0.2

# Upgrade Loft plugin to v2.0.3-beta.15
$ devspace update plugin loft --version v2.0.3-beta.15
[info]   Updating plugin loft to version v2.0.3-beta.15
[done] √ Successfully updated plugin loft
$ devspace list plugins

 Name   Version          Commands   Vars  
 loft   v2.0.3-beta.15   18         2     

# Update the Loft plugin to the latest release without specifying the version
$ devspace update plugin loft       
[info]   Updating plugin loft to version v2.0.2
[done] √ Successfully updated plugin loft
$ devspace list plugins

 Name   Version   Commands   Vars  
 loft   v2.0.2    18         2     
```

**Closed as completed by leventogut** 2022-01-06 13:48 UTC
